name: cryofsl
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - charset-normalizer=3.3.2
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.8
  - ffmpeg=4.3
  - freetype=2.12.1
  - gmp=6.3.0
  - gnutls=3.6.15
  - intel-openmp=2023.1.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.13.0.11
  - libcurand=10.3.9.55
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - ncurses=6.4
  - nettle=3.7.3
  - numpy-base=2.0.1
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=1.1.1w
  - python=3.11.0
  - pytorch=2.3.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - readline=8.2
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - torchtriton=2.3.0
  - typing_extensions=4.12.2
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - addict==2.4.0
    - antlr4-python3-runtime==4.9.3
    - brotli==1.0.9
    - certifi==2025.1.31
    - contourpy==1.3.1
    - cycler==0.12.1
    - einops==0.8.1
    - filelock==3.13.1
    - fonttools==4.56.0
    - fsspec==2025.2.0
    - gmpy2==2.2.1
    - huggingface-hub==0.28.1
    - hydra-core==1.3.2
    - idna==3.7
    - imageio==2.37.0
    - jinja2==3.1.5
    - joblib==1.4.2
    - kiwisolver==1.4.8
    - lazy-loader==0.4
    - markdown-it-py==3.0.0
    - markupsafe==3.0.2
    - matplotlib==3.10.0
    - mdurl==0.1.2
    - mkl-fft==1.3.11
    - mkl-random==1.2.8
    - mkl-service==2.4.0
    - mmcv==1.7.2
    - mmengine==0.10.6
    - monai==1.4.0
    - mpmath==1.3.0
    - networkx==3.4.2
    - numpy==1.26.4
    - omegaconf==2.3.0
    - opencv-python==4.11.0.86
    - openslide-bin==4.0.0.8
    - openslide-python==1.4.2
    - packaging==24.2
    - pandas==2.2.3
    - pillow==9.4.0
    - pip==25.0
    - platformdirs==4.3.6
    - protobuf==5.29.3
    - psutil==7.0.0
    - pycocotools==2.0.8
    - pygments==2.19.1
    - pyparsing==3.2.1
    - pysocks==1.7.1
    - python-dateutil==2.9.0.post0
    - pytz==2025.1
    - pyyaml==6.0.2
    - requests==2.32.3
    - rich==13.9.4
    - safetensors==0.5.2
    - scikit-image==0.25.1
    - scikit-learn==1.6.1
    - scipy==1.15.1
    - seaborn==0.13.2
    - setuptools==75.8.0
    - six==1.17.0
    - sympy==1.13.3
    - tensorboardx==2.6.2.2
    - termcolor==2.5.0
    - threadpoolctl==3.5.0
    - tifffile==2025.1.10
    - timm==1.0.14
    - torch==2.3.0
    - torchaudio==2.3.0
    - torchvision==0.18.0
    - tqdm==4.67.1
    - triton==2.3.0
    - typing-extensions==4.12.2
    - tzdata==2025.1
    - urllib3==2.3.0
    - wheel==0.45.1
    - yapf==0.43.0
